site_name: 「 Pythonic Python 」
theme:
  name: material
  palette:
    primary: black
    accent: deep-orange

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      pygments_style: monokai
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde